# Generated by Django 4.1 on 2022-09-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_birth_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
