# Generated by Django 4.1 on 2022-09-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_time_alter_post_comment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post_comment_reply',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 18, 2, 41309)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 18, 2, 45802)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 18, 2, 47553)),
        ),
    ]
