# Generated by Django 4.1 on 2022-09-13 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_comment_likes_num_post_comment_reply_likes_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares_num',
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends'), (2, 'Only me')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 33, 29, 28189)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 33, 29, 32661)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 9, 33, 29, 33828)),
        ),
    ]
