# Generated by Django 4.1 on 2022-09-13 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_shares_num_post_privacy_alter_post_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='<django.db.models.fields.UUIDField>/cover_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 43, 27, 455039)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 43, 27, 459794)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 43, 27, 460976)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='<django.db.models.fields.UUIDField>/profile_images/'),
        ),
    ]
