# Generated by Django 4.1 on 2022-09-13 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_cover_img_alter_post_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 57, 27, 970817)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 57, 27, 978699)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 57, 27, 980315)),
        ),
        migrations.CreateModel(
            name='User_Imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='blank-profile-picture.png', upload_to='<django.db.models.fields.related.OneToOneField>/profile_images/')),
                ('cover_img', models.ImageField(default='blank-profile-picture.png', upload_to='<django.db.models.fields.related.OneToOneField>/cover_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
