# Generated by Django 4.1 on 2022-09-23 09:12

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_skill_alter_post_time_alter_post_comment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='has_vid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 11, 12, 11, 321343)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 11, 12, 11, 330620)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 11, 12, 11, 332553)),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post_video',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='default-cover.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.CreateModel(
            name='Post_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
        ),
    ]
