# Generated by Django 4.1 on 2022-09-25 08:57

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_post_has_tag_alter_post_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_post', to='core.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 57, 10, 724366)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 57, 10, 730721)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 57, 10, 733022)),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post_video',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='default-cover.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=core.models.Upload.upload_location),
        ),
    ]
