# Generated by Django 4.1 on 2022-09-25 12:18

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post_is_shared_post_shared_post_alter_post_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_of_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 14, 18, 48, 738086)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 14, 18, 48, 743854)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 14, 18, 48, 745045)),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post_video',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='default-cover.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=core.models.Upload.upload_location),
        ),
    ]
