# Generated by Django 4.1 on 2022-09-30 19:55

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_post_time_alter_post_comment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='has_vid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_comment_reply',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_comment_reply',
            name='has_vid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='comment_vid',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 21, 55, 50, 824875)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 21, 55, 50, 831345)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 21, 55, 50, 834795)),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post_video',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='reply_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='reply_vid',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='default-cover.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=core.models.Upload.upload_location),
        ),
    ]
