# Generated by Django 4.1 on 2022-10-04 14:26

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_post_comment_has_img_post_comment_has_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_img',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='reply_vid',
            name='reply',
        ),
        migrations.AlterField(
            model_name='comment_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='comment_vid',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 16, 26, 23, 736265)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 16, 26, 23, 742492)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 16, 26, 23, 745986)),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post_video',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='default-cover.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.DeleteModel(
            name='Post_Share',
        ),
        migrations.DeleteModel(
            name='Reply_Img',
        ),
        migrations.DeleteModel(
            name='Reply_Vid',
        ),
    ]
