# Generated by Django 4.1 on 2022-10-06 19:58

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_reply_img_reply_remove_reply_vid_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='comment_vid',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 58, 53, 35454)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 58, 53, 41659)),
        ),
        migrations.AlterField(
            model_name='post_comment_reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 58, 53, 45108)),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='post_video',
            name='vid',
            field=models.FileField(upload_to=core.models.Upload.upload_post_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='default-cover.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=core.models.Upload.upload_location),
        ),
        migrations.CreateModel(
            name='Followship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 58, 53, 46828))),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
